SELECT USER
FROM DUAL;

--임의회원코드발급
INSERT INTO TMP_MEM (T_MEM_ID, T_MEM_DATE,T_MEM_ALA_DATE) VALUES (DBMS_RANDOM.STRING('X', 10),SYSDATE,SYSDATE);
INSERT INTO TMP_MEM (T_MEM_ID, T_MEM_DATE,T_MEM_ALA_DATE) VALUES (DBMS_RANDOM.STRING('X', 10),SYSDATE,SYSDATE);




-- 회원
-- MEMBER

SELECT * 
FROM MEMBER;

DELETE
FROM MEMBER;

INSERT INTO MEMBER(MEM_ID, MEM_NAME, MEM_ID_ID, MEM_PW, MEM_TEL, MEM_SSN1, MEM_SSN2, MEM_NICKNAME, MEM_ZIPCODE, MEM_ADDR
, MEM_ADDR_DETAIL, MEM_LATITUDE, MEM_LONGTITUDE, MEM_IMG, TMP_MEMBER_ID)
VALUES(SEQ_MEMBER_ID.NEXTVAL, '홍길동', 'kiwifirst', 'JAVA002$', '01011111111', '221231','1111111', '키위첫번째', 67890, 
'서울시 마포구 111-11 길', '101호', '37.556556', '126.919550'
, 'C://~~', 105);





CREATE OR REPLACE PROCEDURE PRC_TMP_MEMBER
( 
 V_MEM_NAME            IN MEMBER.MEM_NAME%TYPE
, V_MEM_ID_ID           IN MEMBER.MEM_ID_ID%TYPE
, V_MEM_PW              IN MEMBER.MEM_PW%TYPE
, V_MEM_TEL             IN MEMBER.MEM_TEL%TYPE
, V_MEM_SSN1            IN MEMBER.MEM_SSN1%TYPE
, V_MEM_SSN2            IN MEMBER.MEM_SSN2%TYPE
, V_MEM_NICKNAME        IN MEMBER.MEM_NICKNAME%TYPE
, V_MEM_ZIPCODE         IN MEMBER.MEM_ZIPCODE%TYPE
, V_MEM_ADDR            IN MEMBER.MEM_ADDR%TYPE
, V_MEM_ADDR_DETAIL     IN MEMBER.MEM_ADDR_DETAIL%TYPE
, V_MEM_LATITUDE        IN MEMBER.MEM_LATITUDE%TYPE
, V_MEM_LONGTITUDE      IN MEMBER.MEM_LONGTITUDE%TYPE
, V_MEM_IMG             IN MEMBER.MEM_IMG%TYPE
)
IS
    TEMP_RANNUM VARCHAR2(10);
BEGIN
    --NUM := TBL_INSA_SQE.NEXTVAL;
    -- 데이터 입력H
    TEMP_RANNUM := DBMS_RANDOM.STRING('X', 10);
    INSERT INTO TMP_MEM (T_MEM_ID, T_MEM_DATE,T_MEM_ALA_DATE) 
    VALUES (TEMP_RANNUM, SYSDATE, SYSDATE);

    INSERT INTO MEMBER(MEM_ID, MEM_NAME, MEM_ID_ID, MEM_PW, MEM_TEL, MEM_SSN1, MEM_SSN2, MEM_NICKNAME, MEM_ZIPCODE, MEM_ADDR
    , MEM_ADDR_DETAIL, MEM_LATITUDE, MEM_LONGTITUDE, MEM_IMG, TMP_MEMBER_ID)
    VALUES(SEQ_MEMBER_ID.NEXTVAL, V_MEM_NAME, V_MEM_ID_ID, V_MEM_PW, V_MEM_TEL, V_MEM_SSN1, V_MEM_SSN2, V_MEM_NICKNAME, V_MEM_ZIPCODE
    , V_MEM_ADDR, V_MEM_ADDR_DETAIL, V_MEM_LATITUDE, V_MEM_LONGTITUDE, V_MEM_IMG, TEMP_RANNUM);

    COMMIT;
END;






INSERT INTO TMP_MEM (T_MEM_ID, T_MEM_DATE,T_MEM_ALA_DATE) 
VALUES (DBMS_RANDOM.STRING('X', 10),SYSDATE,SYSDATE);



EXEC PRC_TMP_MEMBER('홍길동', 'kiwifirst', 'JAVA002$', '01011111111', '221231','1111111', '키위첫번째', '67890', '서울시 마포구 111-11 길', '101호', '37.556556', '126.919550', '1');;

select *
from nls_session_parameters
where parameter='NLS_DATE_FORMAT';


ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD HH24:MI:SS';


EXEC PRC_INSERT_V(10000,'22222222222','22222222222','환불','입금',1,2,'12323','서울특별시 마포구 ','202호','24.23232','34.4242','2023-01-02 21:00:00','2023-01-02 22:00:00','SQL문이 몇개고',1,100);


SELECT *
FROM V;


ROLLBACK;



SELECT A.MEM_ID, A.NAME, A.DEPART_ID, B.DEPART_NAME
FROM  PET P, PET_SHARE S
WHERE P.P_SHA_ID = S.P_SHA_ID

------------------------------------영역 잡아서 컴파일


CREATE VIEW
AS
SELECT *
FROM S_APPLY Y
JOIN S_ALLOW W
ON Y.S_APP_ID = W.S_APP_ID;

SELECT *
FROM CERT;


SELECT *
FROM FOS_SITTER;





